### ISSUE TITLE
TWL에서 본인의 깃헙 아이디로 만든 폴더에 커밋하기

### ISSUE THREAD

**Issue by corazzon** [dataitgirls2/TWL#141]
@LunarKim @jy617lee @ddongule @chacha816 
어제 TWL을 작성해 주셨는데 본인이 작성한 내용이 반영이 안 되어 당황하셨을 수도 있을 것 같아요.
일부는 왜 내가 수정한 파일에 다른 분의 내용이 같이 있을까?하셨던 분도 계실거 같고요.

컨플릭은 다음 수업에서 의도하고 있었는데 이번 수업에서 자연스럽게 겪으시게 되었어요 :)
오류가 나도 당황하지 않으셔도 괜찮아요. 본인이 커밋한 내용이 컨플릭으로 지워졌더라도 히스토리에서 확인해 보실 수 있습니다.

컨플릭이 났던 이유는 본인의 폴더가 아닌 상위 폴더에 마크다운 파일을 생성하고 커밋했기 때문이에요.
같은 파일을 여러 명이 수정했기 때문에 풀리퀘가 머지되지 않아 질문해 주신 분들도 계셨어요.
다음 수업에서 이렇게 잘못 커밋한 내용을 변경하거나 파일을 이동하거나 이름을 변경하는 것을 수업에서 다룰 예정이에요.
월요일 TWL부터는 본인의 폴더에 마크다운 파일을 생성해 보세요. :)

**Comment by LunarKim** [comment]
선생님 데잇걸즈 2기 김문희입니다!

컨플릭이 난거였군요!! ㅎㅎ 다음주 수업도 기대됩니다. 얼른 배우고 싶어요~~

항상 감사합니다.

김문희.

2018-07-01 19:03 GMT+09:00 Joeun Park <notifications@github.com>:
